name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: apt-get install xorg-dev libglu1-mesa-dev
    - name: cmake generation
      run: cmake -B build-linux -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: cd build-linux && make -j$(nproc)
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
